name: Telegram Bot

on:
  schedule:
    - cron: "0 14 * * 5"  # ✅ venerdì ore 15 Italia (13 UTC)
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - run: npm install node-fetch

      - run: node bot.js
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
